<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tag_status_select</name>
   <tag></tag>
   <elementGuidId>45083e1b-14dc-4afe-b7e4-fa79e46e04b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status-select-16762</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'status']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4eedcc3b-a076-4a02-ad93-6f51462a960b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>c737334b-8533-4a79-bbef-3bc2260de2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d510c463-a557-425b-90a2-e55c2c48c3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>e247de97-7f8a-4aa4-8184-f261f891ccee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e3d6478-2814-4501-8a9d-d00b6bc4af94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PublishedDraftPending</value>
      <webElementGuid>74603753-f0ee-44fa-b64b-4c221ecfd189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status-select-16762&quot;)</value>
      <webElementGuid>5bd96e95-7fa8-4235-a745-78d0a6a03cbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='status']</value>
      <webElementGuid>162b42c5-47c8-4195-9216-32651f99ed53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='botble-ecommerce-forms-product-tag-form']/div[2]/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>15fca09c-0f16-4c38-831e-7867321a2749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>526f16c6-39dd-484b-8f5d-5e2c97798055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page loaded in 0.2 seconds'])[1]/preceding::select[1]</value>
      <webElementGuid>c800f818-8559-4be9-bbdb-62a2b824758c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>573ebc72-6816-493d-a9d1-27cbf375302f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'status-select-16762' and @name = 'status' and (text() = 'PublishedDraftPending' or . = 'PublishedDraftPending')]</value>
      <webElementGuid>8cc3dcf9-d78f-400b-b165-7390641fcd77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
