<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ecommerce_menu</name>
   <tag></tag>
   <elementGuidId>2f3b376a-e6f2-433e-8165-90e14785c1c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cms-plugins-ecommerce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cms-plugins-ecommerce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a555f40-6627-409f-a6d3-5d7a77a420c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle nav-priority-0</value>
      <webElementGuid>c21754bc-eae5-4b21-a2cf-7def72e10ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#cms-plugins-ecommerce</value>
      <webElementGuid>72127f20-bc95-4e21-aac7-3c55065d8ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cms-plugins-ecommerce</value>
      <webElementGuid>e317b659-d87d-4529-9d74-84830edee060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>113b1266-4195-4056-adce-b26481fc4cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-auto-close</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f1cd751b-3e43-4614-a2e0-9dc043d0e081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f7e4e62-4e5e-4c6c-aff5-f1702250a112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc963a14-3134-4b5f-951b-739edfc69404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ecommerce</value>
      <webElementGuid>4fb56260-37f6-406b-a014-f6b79268b699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ecommerce 23</value>
      <webElementGuid>c2566d89-1c15-4459-8a34-9c2e65f5bbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cms-plugins-ecommerce&quot;)</value>
      <webElementGuid>cf0b4d5e-d3f7-4290-913e-1d9edd3daa6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cms-plugins-ecommerce']</value>
      <webElementGuid>9cbfd2f4-b9d4-43b6-af08-033ca731f324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-menu']/ul/li[2]/a</value>
      <webElementGuid>a4d7c79b-00a9-453f-b42a-03a55f6ba568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>aa04b5d7-5ce3-4373-9824-66fa57752a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::a[2]</value>
      <webElementGuid>efe173aa-5e49-4dfe-9802-f085dfa26ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/preceding::a[1]</value>
      <webElementGuid>2fb48513-1ac8-42de-918b-e8579b7707b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#cms-plugins-ecommerce')]</value>
      <webElementGuid>6acb1208-133d-45eb-9b83-0ef7c7c032ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>462a4257-0ed8-4422-b6bb-1d4bf6e69ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#cms-plugins-ecommerce' and @id = 'cms-plugins-ecommerce' and @title = 'Ecommerce' and (text() = ' Ecommerce 23' or . = ' Ecommerce 23')]</value>
      <webElementGuid>a7d31b76-0c00-4d50-ac9a-cd2428cdc83a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
