<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_tags_menu_item</name>
   <tag></tag>
   <elementGuidId>5e979e62-5757-4a27-ad71-503d21760ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cms-plugins-product-tag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cms-plugins-product-tag']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c3389bf-7006-4721-8ff1-ba36e5a3aa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item nav-priority-100</value>
      <webElementGuid>f29ee056-ed7e-46f4-bb60-1fb1b85edf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nest.botble.com/admin/ecommerce/product-tags</value>
      <webElementGuid>05dc8b87-3440-45de-9994-2a02226ecb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cms-plugins-product-tag</value>
      <webElementGuid>ea174bd3-3f7e-44a5-ade9-9c9f69ab0e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Product tags</value>
      <webElementGuid>97111270-45a0-4958-ba1d-f553e6123369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Product tags </value>
      <webElementGuid>b93c87da-1fb5-4449-899c-2728e6ac353e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cms-plugins-product-tag&quot;)</value>
      <webElementGuid>4c43000f-8011-4352-9fa4-d4912cb61632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cms-plugins-product-tag']</value>
      <webElementGuid>09aac49f-fd07-4867-9e26-a17762f9d5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-menu']/ul/li[2]/div/a[11]</value>
      <webElementGuid>93630b7a-4f3e-4604-948b-fd9e7994466d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product categories'])[1]/following::a[1]</value>
      <webElementGuid>6a2492d5-618e-4f4c-9b8c-42708418dcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Inventory'])[1]/following::a[2]</value>
      <webElementGuid>0fc4b608-35eb-45cf-abb0-9e4142da1119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product attributes'])[1]/preceding::a[1]</value>
      <webElementGuid>35ce4fae-3a59-4fdb-8a6b-328dc1a2a635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nest.botble.com/admin/ecommerce/product-tags')]</value>
      <webElementGuid>61165253-dad3-4690-a083-bf3a49e2af41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[11]</value>
      <webElementGuid>f05d7fbc-f8f8-4fa1-b9cf-b58cad7b1aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nest.botble.com/admin/ecommerce/product-tags' and @id = 'cms-plugins-product-tag' and @title = 'Product tags' and (text() = ' Product tags ' or . = ' Product tags ')]</value>
      <webElementGuid>02554782-dd98-4044-8b23-d9a28f717678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
