<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_tags_link</name>
   <tag></tag>
   <elementGuidId>e5ffd798-4f6e-4b38-a498-02da335488e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div/nav/ol/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04377ab4-eaf6-4aab-8191-996f22b4e2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 d-inline-block fs-6 lh-1</value>
      <webElementGuid>9531123b-091f-4560-8e4e-811e5f255f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nest.botble.com/admin/ecommerce/product-tags</value>
      <webElementGuid>13020004-5090-40c8-88fc-1062f82693c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product tags</value>
      <webElementGuid>645f92aa-3f6f-4f87-9ff8-fe45ef8b04a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;d-block d-lg-flex&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-header d-print-none&quot;]/div[@class=&quot;container-xl&quot;]/div[@class=&quot;row g-2 align-items-center&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;page-pretitle&quot;]/nav[1]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item&quot;]/a[@class=&quot;mb-0 d-inline-block fs-6 lh-1&quot;]</value>
      <webElementGuid>c25cf653-f849-433c-94b6-967f0c56db33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/nav/ol/li[3]/a</value>
      <webElementGuid>b28ae3a3-263b-4930-a876-ca56b247e8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Product tags')]</value>
      <webElementGuid>c33ed339-37bc-4eb6-9cf7-c6f0832bbbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ecommerce'])[1]/following::a[1]</value>
      <webElementGuid>f38dc46c-2095-4698-8bf2-0584bb604332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>d71254d0-d9f0-4d20-b4b2-c46d5850d758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New product tag'])[1]/preceding::a[1]</value>
      <webElementGuid>c85b5b4b-7227-4038-8dd1-b0681a871348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nest.botble.com/admin/ecommerce/product-tags')])[2]</value>
      <webElementGuid>b3c21619-f005-463d-b2e6-2cfa16ded175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[3]/a</value>
      <webElementGuid>be726a93-976c-468c-b3f0-c47c03c52776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nest.botble.com/admin/ecommerce/product-tags' and (text() = 'Product tags' or . = 'Product tags')]</value>
      <webElementGuid>6de753b4-c2b1-421e-9b81-6ba0e7d0df42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
