<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tag_list_item</name>
   <tag></tag>
   <elementGuidId>9ec504fb-fe0b-4834-8cc5-3f957ab11b4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-start.column-key-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='botble-ecommerce-tables-product-tag-table']//td[3]//a[normalize-space()='${name}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ad914b53-be0d-4ea5-9127-9133b8671184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-start  column-key-1</value>
      <webElementGuid>2d34b097-8361-496a-b543-9cc4f0055d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Permalink Format</value>
      <webElementGuid>ac553e1b-5b6d-44ab-9ef0-96257ef2aecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botble-ecommerce-tables-product-tag-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-start  column-key-1&quot;]</value>
      <webElementGuid>234601f0-fe75-4e9a-867e-77b78643cbb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='botble-ecommerce-tables-product-tag-table']/tbody/tr/td[3]</value>
      <webElementGuid>dd22e469-6660-4162-ba78-ec6decd6ad1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operations'])[1]/following::td[3]</value>
      <webElementGuid>c1647a27-2007-4603-b7ba-1423e747cfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[4]/following::td[3]</value>
      <webElementGuid>4cfd4c5a-aeca-4f5d-96a2-7afa2e403e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[1]/preceding::td[2]</value>
      <webElementGuid>58761733-bd04-495c-8cdd-ba5afcbc89f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>21de1185-3b07-4704-9eb4-ccb9201c949e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[@id='myTableId']//td[contains(text(),'${expectedValue}')]</value>
      <webElementGuid>c0fb5fc0-bb88-43a8-a3b9-c2242fd39703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
