<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tag_slug_input</name>
   <tag></tag>
   <elementGuidId>b7f4d133-6869-4504-9f23-62f3d50a7828</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slug</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'slug' and @id = 'slug']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slug']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9f76bc2-2f1f-4e71-848d-c3d98884ece1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ps-0</value>
      <webElementGuid>3e3548ae-ce13-4658-9339-e84c69e83240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2412947-a91e-4d69-810f-28f645bc2826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slug</value>
      <webElementGuid>6ce28fbb-cece-4a18-8ee6-d706ee99b3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slug</value>
      <webElementGuid>ac7b4ce1-da4a-45ed-8de3-a3210c86aed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3c9813c7-f228-445a-bace-1de846ce62b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a15b2a2-e443-4a64-a0e9-fba6ba76f442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slug&quot;)</value>
      <webElementGuid>30ecdb9f-0a63-4e02-9fbb-68943d26657a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slug']</value>
      <webElementGuid>1c06662e-4ec3-449b-b60b-475ae73cf82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='botble-ecommerce-forms-product-tag-form']/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>f3ccfcbd-e9bf-4cf7-a378-95161f0f8c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>894e3088-02cb-4967-aa59-94d64877c6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'slug' and @id = 'slug']</value>
      <webElementGuid>25c6dd95-23f6-4eb1-85f9-43bf689fb22a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
